name: Get All SES Templates and Create PR with HTML (Secure API Key)

# Define environment variables for credentials (securely stored in GitHub secrets)
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ vars.AWS_REGION }} # Optional, if not specified in Boto3 configuration

on:
  workflow_dispatch:

jobs:
  get_templates_and_create_pr:  # Unique job name
    runs-on: ubuntu-latest  # Specify the runner environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install boto3

      - name: Fetch SES templates and create PR
        run:  python workflows/create_pr_from_dit_ses.py
          
